### ISSUE TITLE
Invalid SSML request

### ISSUE THREAD

**Issue by nghiapv** [StachePL/ExcelToAmazonPolly#1]
Hi, I've using your program for awhile, Today when I tried the SSML, i went smoothly for the first time but on the second time, I got this problem: http://prntscr.com/j1ll6p. It only works if I delete the first line.

**Comment by StachePL** [comment]
Hello :) I'm glad you're finding the tool useful. 
First thing that comes in mind is that for some reason there's an error in the first entry.
Can you please check if it generates correctly fro the Amazon console?
https://console.aws.amazon.com/polly

It may be due to usage of special characters like ` ' " `. It sometimes happened to me when I was copying text from Word. 
Please let me know of your results. If it works in the console and doesn't work in the app, I'll do my best to fix it fast :) Cheers!

**Comment by nghiapv** [comment]
Hi. Thanks for your support. May I ask you how can I get a log of my session when this error occurs?

**Comment by nghiapv** [comment]
just found out that the problem is caused by "&" symbol.

**Comment by StachePL** [comment]
Oh interesting. I wonder if it has any special meaning in SSML. Logging is not implemented yet. I'm adding it to future features list now :)
Here: #5
